### ISSUE TITLE
Auto checkout on file save not working

### ISSUE THREAD

**Issue by Etchelon** [ivangabriele/vscode-tfs#1]
I have installed VS 2013 and TFS Power Tools but it still won't work.
For Atom I have a plugin, atom-tfs-auto, which does checkout the file automatically (when I open the file, actually, not when saving).

**Comment by ivangabriele** [comment]
Yes I noticed that today. I'll fix that asap !

**Comment by ivangabriele** [comment]
Hi @Etchelon,

It's fixed in the last release I published today (v0.5.0).
