### ISSUE TITLE
VSCode will show failure to save using autosave the first time

### ISSUE THREAD

**Issue by kamranayub** [ivangabriele/vscode-tfs#10]
While the extension _does_ auto-checkout on save, VScode will complain the first time it tries to save when the file is read-only and not checked out. I am using auto-save with after delay enabled. I was confused at first, but then I saw that the extension did successfully check the file out.

Is there a way to make that experience smoother?

**Comment by gamelover42** [comment]
I have also seen this behavior. I didnt even notice it had done the checkout until later.

**Comment by ivangabriele** [comment]
#11 Duplicate
