### ISSUE TITLE
New File annoying error

### ISSUE THREAD

**Issue by oddllc** [ivangabriele/vscode-tfs#11]
If you have a new untitled file open, as a scratchpad, an error keeps occurring on EVERY keypress.  "TFS: Either there is no current file opened or your current file has not been saved."

Error messages like this should not be tied to the key press because if you click Close, and press a key the error is back.

**Comment by terrabite3** [comment]
commit 1c6016ff477a437b3b2abf3cafa131f81340da8f appears to address this issue, but I am still seeing the issue. That is because the latest release is from the day before this fix.

**Comment by ivangabriele** [comment]
It should have been fixed with 0.6.0 release.
