### ISSUE TITLE
TFS: TypeError: Bad argument

### ISSUE THREAD

**Issue by shishenzhezai** [ivangabriele/vscode-tfs#12]
Hello,
I have installed VS 2013 and using TFS , 
Win 7 sp1
VS Code 1.3.1
Any command I execute I get this error 
TFS: TypeError: Bad argument

thanks. looking forward to using this.

**Comment by shishenzhezai** [comment]
it's ok.Thanks.

**Comment by gr00kiter** [comment]
怎么解决的？
