### ISSUE TITLE
In case of more then 100000 files in your local workspace, this plugin shows an error and stops

### ISSUE THREAD

**Issue by StefH** [ivangabriele/vscode-tfs#15]
In case of more then 100000 files in your local workspace, this plugin shows an error and stops.

![2016-09-13_08h16_25](https://cloud.githubusercontent.com/assets/249938/18463455/96d75d20-798a-11e6-8935-06158beceac4.png)

**Comment by ivangabriele** [comment]
Hi @StefH,

Sorry for the late answer. It's not an extension error but a real Team Foundation error as you can see in the reference. [A little Google search can help you with that](https://www.google.com/search?q=tf401190).
