### ISSUE TITLE
New file shows as error

### ISSUE THREAD

**Issue by wrokred** [ivangabriele/vscode-tfs#17]
"TFS: Either there is no current file opened or your current file has not been saved."

Options to close and remember for that file/session.
Or ignore the error for unsaved files starting with Untitled-X

I may be making a new file that I'm setting up before my first save, but a lot of the time I use it to hold data dumps, or notes. And this error reloads itself on each keypress.

**Comment by cskiwi** [comment]
+1

**Comment by Karillion** [comment]
+1 This warning gets very frustrating as it appears constantly.

**Comment by Loetn** [comment]
This also occurs when typing in the 'Debugger for Chrome' extension debug console.

**Comment by kwiss** [comment]
+1

**Comment by ivangabriele** [comment]
Same as #11 : fixed with 0.6.0.
