### ISSUE TITLE
Issue on installing

### ISSUE THREAD

**Issue by mahdib** [ivangabriele/vscode-tfs#18]
Hi dear,
I got a failure on my system when I want to use npm install command.
log file is attached.
[npm-debug.txt](https://github.com/ivangabriele/vscode-tfs/files/517547/npm-debug.txt)

**Comment by ivangabriele** [comment]
Hi @mahdib,

You're not suppose to do the `npm install` yourself when you install the extension. As the error states, the pots-install is looking for `vscode` module which is not installed since VSCode do not install devDependencies.
