### ISSUE TITLE
You are not authorized to access 192.168.10.201\DefaultCollection.

### ISSUE THREAD

**Issue by TheSniper102** [ivangabriele/vscode-tfs#19]
althogh i can access it from visual studio 2015 it give me the following error when try to check in my changes using vs code tfs plugin 
TFS: TF30063: You are not authorized to access 192.168.10.201\DefaultCollection.

i checked the following issue with no help 

[issue #3 ](https://github.com/ivangabriele/vscode-tfs/issues/8)

**Comment by ivangabriele** [comment]
Hi @TheSniper102,

Sorry for the late answer. It's not an extension issued but [a TFS one](https://www.google.com/search?q=TF30063) so I can't help with that on my side.

**Comment by TheSniper102** [comment]
thanks
