### ISSUE TITLE
Any command I execute I get this error

### ISSUE THREAD

**Issue by platonicvizard** [ivangabriele/vscode-tfs#2]
TFS: You need to save your file somewhere before.
The file is saved.
This an existing visual studio project where TFS is working fine.

**Comment by ivangabriele** [comment]
I'll try to reproduce the case. It may be linked to [this bug](https://github.com/ivangabriele/vscode-tfs/issues/1).

**Comment by ivangabriele** [comment]
Hi @platonicvizard,

It should be fixed in the last release I published today (v0.5.0) !

**Comment by platonicvizard** [comment]
It works. Thanks for getting this fix so promptly.
