### ISSUE TITLE
TFS: A new version (undefined), is available. on VS code open

### ISSUE THREAD

**Issue by gamelover42** [ivangabriele/vscode-tfs#21]
Every time I open VS code I now receive the following warning: TFS: A new version (undefined), is available.

I am running VS code 1.6.1 on Windows 7 x64

**Comment by ivangabriele** [comment]
Hi @gamelover42,

Sorry for the ate answer. Did you try to update your VSCode to the last version (I think it's 1.10.1 at the moment) to see if you still get this error ?

**Comment by gamelover42** [comment]
It is working now.

**Comment by ivangabriele** [comment]
@gamelover42 Happy to know that :)
