### ISSUE TITLE
Unable to determine the source control server.

### ISSUE THREAD

**Issue by CutieDaisy** [ivangabriele/vscode-tfs#26]
When I try to issue any of the available commands, it shows an error 'TFS:Unable to determine the source control server.'

**Comment by ivangabriele** [comment]
Hi @CutieDaisy,

Sorry for the late answer. It's not an extension error but a real Team Foundation error because the files are not under TF version control. This extension is just a helper : if you can't see your files in TFS within Visual Studio, you obviously won't see them either in VS Code.
