### ISSUE TITLE
Where do I specify the TFS ip address ?

### ISSUE THREAD

**Issue by anishswiss** [ivangabriele/vscode-tfs#27]
Hi,

I have my angular 2 code in visual studio code. I would like to check in the complete folder in TFS.

I have installed this extension in my visual studio code; 

but I don't know 

1. Where to specify my TFS url (ip address and/or port)
2. How to check in my complete project (first time).

Could you please give me an answer to these questions. I could not find any documentation regarding this.

Thanks
Anish Mohan

**Comment by ivangabriele** [comment]
Hi @anishswiss,

Sorry for the late answer but extension can't work without having a real Visual Studio + TFS installed. Unfortunately Microsoft didn't develop any standalone TFS solution. It's in your Visual Studio with TFS that you have to set up your TFS server url.
