### ISSUE TITLE
Error: TFS: There is no working folder mapping for C:\Program Files (x86)\Microsoft VS Code\undefined.

### ISSUE THREAD

**Issue by aaegroupguy** [ivangabriele/vscode-tfs#3]
Hello, I am trying to test a simple 1 line file using your extension.

It installed OK.  When I do alt-t and select GET

I am getting these errors

TFS: TF30063: You are not authorized to access lenovo5\DefaultCollection.

TFS: There is no working folder mapping for C:\Program Files (x86)\Microsoft VS Code\undefined.

My levovo5]DefaultCollection is accessible from VS 2015 Source Control Explorer

thanks.  looking forward to using this.

**Comment by ivangabriele** [comment]
Hi !

It may be hard to reproduce. Have you multiple TFS credentials (accounts) ?

**Comment by selaelop** [comment]
Yes
