### ISSUE TITLE
 Error when using visual studio 2017  "TFS: TypeError: Bad argument"

### ISSUE THREAD

**Issue by phcc2306** [ivangabriele/vscode-tfs#46]
I installed visual studio 2017.
I put the tfs in it and it worked correctly.
When trying to use in vscode, the following error occurs:
"TFS: TypeError: Bad argument"

I saw that the Visual Studio 2017 TF.exe path is different from the other versions.
how can I solve?

Thank you

**Comment by mirkogit** [comment]
Same error here.

**Comment by ivangabriele** [comment]
@phcc2306 @mirkogit It has been fixed with the last version.
