### ISSUE TITLE
Receiving error "command 'vscode-tfs.list'

### ISSUE THREAD

**Issue by anomaly11** [ivangabriele/vscode-tfs#49]
Recently, I've started receiving the error  "command 'vscode-tfs.list' not found" when pressing Alt + T.  I am unable to get to any of the commands and neither are my changes tracked anymore.  Any help is greatly appreciated.

![vscode_tfs_ext_error](https://user-images.githubusercontent.com/44806007/48064729-48ee9100-e18e-11e8-9d0e-1514bd1eccec.png)

**Comment by kwasmich** [comment]
I'm encountering the same issue. The TFS extension is currently not usable.

**Comment by ivangabriele** [comment]
I will check that right now.

**Comment by ivangabriele** [comment]
@anomaly11 @kwasmich What version of VSCode do you have ?

**Comment by lulzatron** [comment]
I haven't been able to get the extension to work at all as of today. I tried pulling down the most recent branch to build the extension manually, but "npm run compile" doesn't appear to actually output anything other than test files.

My VS Code is on 1.28.2 and the extension is referring to version 0.7.0

**Comment by ivangabriele** [comment]
@devinvoss `0.7.0` is the version of the extension itself. The required VSCode version is the one declared [there](https://github.com/ivangabriele/vscode-tfs/blob/master/package.json#L11): `"vscode": "^1.28.2"`.

In any case you have the good version so I need to investigate that. Trying to rebuild it yourself won't solve the issue which surely comes from the commands binding.

**Comment by ivangabriele** [comment]
I just published the **v0.7.1** hoping it will fix your issue. Please tell me if it works after the update.

**Comment by anomaly11** [comment]
>           @anomaly11 @kwasmich What version of VSCode do you have ?

Sorry for the delay.  I am running VS Code version 1.28.2

**Comment by anomaly11** [comment]
>           I just published the **v0.7.1** hoping it will fix your issue. Please tell me if it works after the update.

I tried the update and I am able to get the commands now but they don't seem to do anything.  My changes are still not tracked.

**Comment by devinvoss** [comment]
@ivangabriele Progress! In tfsExec.js we just need to update method calls from the **utils** object to reference the **default** property. I got this to run locally with those changes. I'd create a pull request but I don't have access to git on my work computer -_-

**Comment by kwasmich** [comment]
> 
> 
> @anomaly11 @kwasmich What version of VSCode do you have ?

I'm also using Code 1.28.2. Just downgraded to 1.27.2 and there it works just fine.

**Comment by kwasmich** [comment]
> 
> 
> > ```
> >       I just published the **v0.7.1** hoping it will fix your issue. Please tell me if it works after the update.
> > ```
> 
> I tried the update and I am able to get the commands now but they don't seem to do anything. My changes are still not tracked.

Same for me.

**Comment by ivangabriele** [comment]
@devinvoss @kwasmich I didn't do the full switch to TS. I just published the **v0.7.2**.

**Comment by anomaly11** [comment]
I am back up and running.  The latest version seemed to do the trick.  Thanks for your hard work!

**Comment by kwasmich** [comment]
> 
> 
> @devinvoss @kwasmich I didn't do the full switch to TS, that's why it messed up with the mix between requires, imports & exports. I just published the **v0.7.2**, I'm refactoring most of it.

Functionality restored! Thanks!

**Comment by ivangabriele** [comment]
You're welcome !
