### ISSUE TITLE
How to configure the connection?

### ISSUE THREAD

**Issue by rneild** [ivangabriele/vscode-tfs#7]
Hi - how do we configure the connection details?

**Comment by ivangabriele** [comment]
Hi,

You can't do that within this extension. For now, you need to have a working TFS connection already set up via Visual Studio. I'll look if it's possible to make it stand-alone in the next weeks.

**Comment by rneild** [comment]
That makes sense and it will work fine. But if you were telling me this with that bold message at the top of the front page then I did not make the connection or understand it to mean that.  My mistake perhaps. I appreciate your quick answer and your work to build this.

**Comment by matijaabicic** [comment]
That means no way to get this to work on a non-windows platform?

**Comment by jennylu89** [comment]
Hello, Thanks for creating this awesome extension! Is there any progress on making this extension accessible with its own connection?
