### ISSUE TITLE
TFS: TF30063: You are not authorized to access [name].visualstudio.com\DefaultCollection

### ISSUE THREAD

**Issue by amolotkov** [ivangabriele/vscode-tfs#8]
Hello, 
I'have VS 2015 Professional with multiple TFS connections. Any command (get/check in/check out) results in the following error:
TFS: TF30063: You are not authorized to access purely-crm.visualstudio.com\DefaultCollection.

Works fine from within VS

**Comment by amolotkov** [comment]
Sorry, I guess there was an issue with my VS, all works fine now/

**Comment by ivangabriele** [comment]
Indeed this is an error linked with TFS usage itself :)

**Comment by blalond** [comment]
I saw this same error but now it went away. I'm not sure which fixed it: run vscode as administrator once, or install tfs global (npm install -g tfs).

**Comment by ranjan-ranjan** [comment]
http://www.niranjankala.in/post/How-to-fix-error-TFS-connection-error-You-are-not-authorized-to-access-%E2%80%A6
