### ISSUE TITLE
[Warn] TFS: A new version (undefined) is available

### ISSUE THREAD

**Issue by elliz** [ivangabriele/vscode-tfs#9]
Win 8.1
VS Code 1.2.0 (May 2016)
VS Code Insiders installed

Open VS Code and attached message appears ... but with no way to install update

![a new version undefined is available](https://cloud.githubusercontent.com/assets/1436701/15924072/4214df18-2e28-11e6-9cd0-afa7db867cbe.png)

**Comment by ivangabriele** [comment]
Hi @elliz,

That's strange. It's supposed to check on this Github API uri : https://api.github.com/repos/ivangabriele/vscode-tfs/releases/latest and get the `tag_name` property.

What's your TFS version (F1 > `>ext` > **Show Installed Extensions** ?

**Comment by elliz** [comment]
0.5.2

It has stopped doing it now ... may only have been a strange artifact from
installing nightly VSCode in parallel with Stable.

Thanks for getting back to me

Sam

On 11 June 2016 at 16:15, Ivan Gabriele <notifications@github.com> wrote:

> Hi @elliz <https://github.com/elliz>,
>
> That's strange. It's supposed to check on this Github API uri :
> https://api.github.com/repos/ivangabriele/vscode-tfs/releases/latest and
> get the tag_name property.
>
> What's your TFS version (F1 > >ext > *Show Installed Extensions* ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ivangabriele/vscode-tfs/issues/9#issuecomment-225368962>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABXsHRqGzsPZaN2G3d8kNW8ptA5NgeSAks5qKtD4gaJpZM4IxwlA>
> .
>



-- 
Sam Ellis
m: 07775 681 815
t: @elliz

**Comment by ivangabriele** [comment]
No problem :)
